# Generated by Django 5.2.12 on 2026-06-01 10:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Adarsh ID Cards', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone1', models.CharField(blank=True, help_text='First phone number with country code e.g. 919876543210', max_length=20)),
                ('phone2', models.CharField(blank=True, help_text='Second phone number with country code e.g. 919876543211', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('is_active', models.BooleanField(default=True, help_text='Active/Inactive toggle for business details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
            },
        ),
        migrations.CreateModel(
            name='WebsiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('live', 'Live'), ('draft', 'Draft')], default='live', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Status',
                'verbose_name_plural': 'Website Status',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('email_retry_count', models.IntegerField(default=0)),
                ('email_last_attempt', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='website_con_status_53fdd9_idx'), models.Index(fields=['email_status'], name='website_con_email_s_69be1a_idx'), models.Index(fields=['created_at'], name='website_con_created_c6daa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='website_faq_is_acti_73bacf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-shield-alt', help_text='Font Awesome icon class (e.g., fas fa-star)', max_length=50)),
                ('number', models.PositiveIntegerField(default=1, help_text='Display order/number')),
                ('highlight', models.CharField(blank=True, help_text='Highlight tags (comma separated)', max_length=255)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'number'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='website_fea_is_acti_6bd60f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fas fa-folder', help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default categories cannot be deleted')),
                ('is_bento', models.BooleanField(default=False, help_text='Show in the bento grid section')),
                ('bento_size', models.CharField(choices=[('large', 'Large'), ('wide', 'Wide'), ('normal', 'Normal')], default='normal', help_text='Card size in bento grid', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Optional SEO description override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Category',
                'verbose_name_plural': 'Portfolio Categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='website_por_is_acti_2087eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('reviewer_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('reviewer_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('reviewer_title', models.CharField(blank=True, help_text='e.g., Principal, Admin Head', max_length=255)),
                ('reviewer_school', models.CharField(blank=True, max_length=255)),
                ('reviewer_avatar', models.ImageField(blank=True, null=True, upload_to='images/Avatars/')),
                ('attachment_image', models.ImageField(blank=True, null=True, upload_to='images/TestimonialAttachments/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('tag', models.CharField(blank=True, help_text='e.g. Quality, Delivery', max_length=100)),
                ('text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['is_active', '-review_date'], name='website_tes_is_acti_632bfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(help_text='Client logo image', upload_to='images/Clients/')),
                ('website_is_visible', models.BooleanField(db_index=True, default=True)),
                ('website_display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Client Logo',
                'verbose_name_plural': 'Website Client Logos',
                'ordering': ['website_display_order', '-created_at'],
                'indexes': [models.Index(fields=['website_is_visible', 'website_display_order'], name='website_web_website_77e858_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Products/')),
                ('orientation', models.CharField(blank=True, choices=[('square', 'Square'), ('portrait', 'Portrait'), ('landscape', 'Landscape'), ('featured', 'Featured'), ('', 'Default')], default='', max_length=20)),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Reel')], default='image', max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='Video URL for video/reel items')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='videos/Portfolio/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, help_text='Optional SEO title override', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Optional SEO description override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='website_por_is_acti_fe86a4_idx'), models.Index(fields=['is_active', 'is_featured'], name='website_por_is_acti_f28356_idx'), models.Index(fields=['is_active', '-created_at'], name='website_por_is_acti_015288_idx'), models.Index(fields=['category', 'is_active', 'order'], name='website_por_categor_5f0a22_idx')],
            },
        ),
    ]
