# Generated by Django 5.2.12 on 2026-06-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='tagline',
        ),
    ]
