# Generated by Django 5.2.12 on 2026-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_businessdetails_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('path', models.CharField(max_length=255)),
                ('referer', models.CharField(blank=True, max_length=500, null=True)),
                ('channel', models.CharField(db_index=True, default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Visitor Hit',
                'verbose_name_plural': 'Visitor Hits',
                'ordering': ['-created_at'],
            },
        ),
    ]
