# Generated by Django 5.2.12 on 2026-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_visitorhit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='app_link',
            field=models.CharField(blank=True, default='com.adarshid.app', help_text='Android app package ID (e.g. com.adarshid.app) or full Play Store URL', max_length=255),
        ),
    ]
