# Generated by Django 5.2.12 on 2026-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_app_link_to_business_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteclientlogo',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='app_link',
            field=models.CharField(blank=True, default='https://play.google.com/store/apps/details?id=com.adarshid.app&pcampaignid=web_share', help_text='Android app package ID (e.g. com.adarshid.app) or full Play Store URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='websiteclientlogo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Client logo image', null=True, upload_to='images/Clients/'),
        ),
    ]
