# Generated by Django 5.2.12 on 2026-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_websiteclientlogo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteclientlogo',
            name='total_records',
            field=models.PositiveIntegerField(default=0, help_text='Total ID card records for this client (synced from panel)'),
        ),
    ]
