# Generated by Django 5.2.12 on 2026-05-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_portfolioitem_website_por_is_acti_015288_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(help_text='Client logo image', upload_to='images/Clients/')),
                ('website_is_visible', models.BooleanField(db_index=True, default=True)),
                ('website_display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Client Logo',
                'verbose_name_plural': 'Website Client Logos',
                'ordering': ['website_display_order', '-created_at'],
                'indexes': [models.Index(fields=['website_is_visible', 'website_display_order'], name='website_web_website_77e858_idx')],
            },
        ),
    ]
