# Generated by Django 5.2.12 on 2026-06-01 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('mobile', 'Mobile App/Phone')], max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Device Session',
                'verbose_name_plural': 'User Device Sessions',
            },
        ),
    ]
