# Generated by Django 5.2.12 on 2026-06-01 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['user', 'device_type'], name='accounts_us_user_id_931c37_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicesession',
            index=models.Index(fields=['last_active'], name='accounts_us_last_ac_acb9bf_idx'),
        ),
    ]
